//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUser
    {
        public int id_usera { get; set; }
        public string username_usera { get; set; }
        public string password_usera { get; set; }
        public string role_usera { get; set; }
    }
}
