//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sudija
    {
        public string ime_sudije { get; set; }
        public string prezime_sudije { get; set; }
        public int id_sudije { get; set; }
        public string nacionalnost_sudije { get; set; }
        public Nullable<int> liga_id_lige { get; set; }
    
        public virtual Liga Liga { get; set; }
    }
}
