//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferistorija
    {
        public int id { get; set; }
        public string klub { get; set; }
        public Nullable<int> igrac_id_igraca { get; set; }
        public string datum { get; set; }
    
        public virtual Igrac Igrac { get; set; }
    }
}
